In [49]:
import pandas as pd 
import numpy as np

In [2]:
# step-1: create df using list
name=['Ramesh','Kishore','Joseph']

In [3]:
#pd.DataFrame(data,index,columns)

In [6]:
pd.DataFrame(name,index=['A','B','C'],columns=['Names'])

     Names
A   Ramesh
B  Kishore
C   Joseph

In [10]:
#step-2:-
name=['Ramesh','Kishore','Joseph']
age=[22,23,24]
pd.DataFrame(zip(name,age),columns=['Names','Age'])

     Names  Age
0   Ramesh   22
1  Kishore   23
2   Joseph   24

In [16]:
# step-3:- Create a df using dictionary
d={'Names':['Ramesh','Kishore','Joseph'],
   'Age':[20,22,23],
   'City':['Koppedu','Puttur','Tirupati']}
d

{'Names': ['Ramesh', 'Kishore', 'Joseph'],
 'Age': [20, 22, 23],
 'City': ['Koppedu', 'Puttur', 'Tirupati']}

In [17]:
pd.DataFrame(d)

     Names  Age      City
0   Ramesh   20   Koppedu
1  Kishore   22    Puttur
2   Joseph   23  Tirupati

In [18]:
# step-4: Selection updation and add column
# select the column
# update the column
# Add new column

In [32]:
d={'Names':['Ramesh','Kishore','Joseph'],
   'Age':[20,22,23]}
df=pd.DataFrame(d)
df

     Names  Age
0   Ramesh   20
1  Kishore   22
2   Joseph   23

In [33]:
# selection
df['Names']

0     Ramesh
1    Kishore
2     Joseph
Name: Names, dtype: object

In [34]:
df['names']

KeyError: 'names'

In [35]:
# uppdation
df['Age']

0    20
1    22
2    23
Name: Age, dtype: int64

In [43]:

df['City']=['koppedu','Hyd','Tirupati',]
df

     Names  Age      City
0   Ramesh   20   koppedu
1  Kishore   22       Hyd
2   Joseph   23  Tirupati

In [44]:
# specific value
df.replace('Ramesh','Dhanusha')

      Names  Age      City
0  Dhanusha   20   koppedu
1   Kishore   22       Hyd
2    Joseph   23  Tirupati

In [47]:
# inplace = we need to python
#           out put should be overwrite 
df.replace('Ramesh','Dr.Dhanusha',inplace=True)
df

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2       Joseph   23  Tirupati

In [60]:
# condition
df['Age']=np.where(df['Names']=='Joseph',65,df['Age'])
df

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2       Joseph   65  Tirupati

In [52]:
l=[]
for i,j in zip(df['Names'],df['Age']):
    if  i=='Joseph':
        l.append(25)
    else:
        l.append(j)
df['Age']=l

In [53]:
df

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2       Joseph   25  Tirupati

In [61]:
# how to drop a column

In [67]:
df

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2       Joseph   65  Tirupati

In [65]:
#df.drop(labels,axis,index,columns)
#df.drop==== i can drop column, or i can drop index
# labels === either column or index 
#df.drop('City') # THIS CITY MIGHT BE INDEX , OR MIGHT BE COLUMNS
# Python ceckes axis =0

In [77]:
df.drop('City',axis=1) # inplace

         Names  Age
0  Dr.Dhanusha   20
1      Kishore   22
2       Joseph   65

In [78]:
df.drop(1,axis=0)

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
2       Joseph   65  Tirupati

In [79]:
df.drop(0,axis=0)

     Names  Age      City
1  Kishore   22       Hyd
2   Joseph   65  Tirupati

In [80]:
df.replace('Joseph','G.JOseph')

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2     G.JOseph   65  Tirupati

In [81]:
df.drop(2,axis=0)

         Names  Age     City
0  Dr.Dhanusha   20  koppedu
1      Kishore   22      Hyd

In [82]:
df

         Names  Age      City
0  Dr.Dhanusha   20   koppedu
1      Kishore   22       Hyd
2       Joseph   65  Tirupati

In [88]:
df=df.drop(index=[1],columns=['City'])
df

         Names  Age
0  Dr.Dhanusha   20
2       Joseph   65